name: Spellcheck Action
on: [push, pull_request]
jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: rojopolis/spellcheck-github-actions@0.35.0
      name: Spellcheck
      with:
        config_path: .spellcheck.yml # put path to configuration file here
        task_name: Markdown
